/**:
  scanning_node:
    ros__parameters:
      joint_topic: "joint_trajectory_controller/joint_trajectory"
      joy_topic: "joy"
      home_button: 7
      viewpoint_button: 6
      angle_step: 1.047
      angular_velocity: 0.8